### ISSUE TITLE
How to configure custom Audit Policy?

### ISSUE THREAD

**Issue by ThomasVitt** [openshift/cluster-openshift-apiserver-operator#375]
Hello,

with Openshift 3.x we had the ability to configure advanced master api audit logging by providing a custom policy:
https://docs.openshift.com/container-platform/3.11/install_config/master_node_configuration.html#master-node-config-advanced-audit
https://kubernetes.io/docs/tasks/debug-application-cluster/audit/

How can this be accomplished with Openshift 4.x ? The apiserver config is supposably generated by the opensshift-apiserver-operator, and provided by the configmap "config" in namespace "openshift-apiserver". But there the default audit policy is provided as JSON inline.  

Thanks for your help, 
Thomas

**Comment by sttts** [comment]
https://github.com/openshift/enhancements/blob/master/enhancements/kube-apiserver/audit-policy.md comes with 4.6.

**Comment by ThomasVitt** [comment]
OK, Thanks!
