### ISSUE TITLE
error synchronizing: clusterrole.rbac.authorization.k8s.io "aggregated-apiserver-clusterrole" not found

### ISSUE THREAD

**Issue by wking** [openshift/cluster-openshift-apiserver-operator#38]
@RobertKrawitz is seeing:

```
Warning Unhealthy 39m kubelet, dev1-master-0 Readiness probe failed: Get https://10.2.0.19:8443/healthz: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Warning Unhealthy 38m kubelet, dev1-master-0 Readiness probe failed: HTTP probe failed with statuscode: 500
E1017 15:21:07.774244 1 cache.go:332] error synchronizing: clusterrole.rbac.authorization.k8s.io "aggregated-apiserver-clusterrole" not found
```

in the `apiserver` pod in the `openshift-apiserver` namespace using `openshift-install` v0.2.0-23-g079fe51f8f6b4e9ec5f084e620d1adf13c0adbe5 (I dunno what cluster-opernshift-apiserver-operator image) on libvirt.  Is this a known issue?

**Comment by deads2k** [comment]
@RobertKrawitz can we get a gist of a log dump and the yaml output for your apiserver pod?  We know there's a bad rolebinding somewhere, but the "normal" symptom is a log message and no other effect.

**Comment by RobertKrawitz** [comment]
I'll fire it up but probably won't have a dump until later this afternoon.

**Comment by RobertKrawitz** [comment]
Attached are the pod description, pod YAML, and pod logs.  The logs are compacted by eliding duplicate lines and printing the number of reps in (parentheses) after the line.

I will keep the cluster up for now in case you want more info.

[apiserver.desc.txt](https://github.com/openshift/cluster-openshift-apiserver-operator/files/2489489/apiserver.desc.txt)
[apiserver.yaml.txt](https://github.com/openshift/cluster-openshift-apiserver-operator/files/2489490/apiserver.yaml.txt)
[apiserver-logs.txt](https://github.com/openshift/cluster-openshift-apiserver-operator/files/2489491/apiserver-logs.txt)

**Comment by RobertKrawitz** [comment]
I can no longer reproduce this.

**Comment by smarterclayton** [comment]
I'm still seeing this on todays clusters
