### ISSUE TITLE
Operator fails with 'Generation: expected: 3, actual: 5' 

### ISSUE THREAD

**Issue by vrutkovs** [openshift/cluster-openshift-apiserver-operator#86]
See https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/10695/pull-ci-openshift-openshift-ansible-master-e2e-gcp/1078
```
results:
    cmd: /bin/oc get ClusterOperator openshift-cluster-openshift-apiserver-operator -o json -n default
    results:
    - apiVersion: config.openshift.io/v1
      kind: ClusterOperator
      metadata:
        creationTimestamp: '2018-12-06T15:25:26Z'
        generation: 1
        name: openshift-cluster-openshift-apiserver-operator
        resourceVersion: '12310'
        selfLink: /apis/config.openshift.io/v1/clusteroperators/openshift-cluster-openshift-apiserver-operator
        uid: 27de192a-f96b-11e8-928e-42010af00002
      spec: {}
      status:
        conditions:
        - lastTransitionTime: '2018-12-06T15:40:29Z'
          status: 'False'
          type: Failing
        - lastTransitionTime: '2018-12-06T15:40:29Z'
          status: 'True'
          type: Available
        - lastTransitionTime: '2018-12-06T15:40:29Z'
          message: 'Generation: expected: 3, actual: 5'
          reason: DesiredStateNotYetAchieved
          status: 'True'
          type: Progressing
        extension: null
        version: ''
```

**Comment by mfojtik** [comment]
@vrutkovs i believe this is transient error. The operator is reporting available==true, the problem here is that we just not cleaning up the failing status.

/cc @deads2k 
/cc @sanchezl

**Comment by vrutkovs** [comment]
Right, this happens on ~10% of installs and doesn't seem to be reporting a real issue. 

These conditions are used in playbooks to wait for operator to complete setup though

**Comment by vrutkovs** [comment]
This now happens fairly often and blocks ingress operator install: operator gets stuck on `'Generation: expected: 3, actual: 2'` (numbers may vary, but this is most frequent combination) and ingress is not deployed

**Comment by vrutkovs** [comment]
This causes CVO to stumble and blocks other operators - e.g. machine approver, so some CI runs don't get CSR approved and return empty logs

**Comment by deads2k** [comment]
@abhinavdahiya how long the CVO wait to settle?  Also, any idea why the CI isn't pulling pod logs?

**Comment by abhinavdahiya** [comment]
> how long the CVO wait to settle?

it waits as long it takes. CVO keeps retrying always...

>  Also, any idea why the CI isn't pulling pod logs?

hmm, do you have any particular one?

**Comment by deads2k** [comment]
> hmm, do you have any particular one?

the one linked from the description. https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/10695/pull-ci-openshift-openshift-ansible-master-e2e-gcp/1078

**Comment by abhinavdahiya** [comment]
> > hmm, do you have any particular one?
> 
> the one linked from the description. https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-ansible/10695/pull-ci-openshift-openshift-ansible-master-e2e-gcp/1078

This is ansible ci job, i have no clue how it s setup. :innocent:

**Comment by vrutkovs** [comment]
>Also, any idea why the CI isn't pulling pod logs?

Investigated this with @eparis in Slack.
CVO starts operators.
apiserver gets stuck on `Expected generation`
CVO never calls machine-approver operator
node csrs are stuck in Pending and any `oc log` call returns `tls error`. As a result we can get events, pods list and nodes - but not the logs for pods

**Comment by eparis** [comment]
```
$ oc get clusteroperator -o yaml openshift-cluster-kube-apiserver-operator
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  creationTimestamp: 2018-12-12T15:18:13Z
  generation: 1
  name: openshift-cluster-kube-apiserver-operator
  resourceVersion: "97258"
  selfLink: /apis/config.openshift.io/v1/clusteroperators/openshift-cluster-kube-apiserver-operator
  uid: 2451d21c-fe21-11e8-a512-021a424c72ca
spec: {}
status:
  conditions:
  - lastTransitionTime: 2018-12-12T19:01:09Z
    status: "False"
    type: Failing
  - lastTransitionTime: 2018-12-12T19:01:09Z
    message: 3 of 3 nodes are at revision 1
    status: "True"
    type: Available
  - lastTransitionTime: 2018-12-12T19:01:09Z
    message: 0 of 3 nodes are at revision 1
    reason: AllNodesAtLatestRevision
    status: "False"
    type: Progressing
  extension: null
  version: ""
```

Somehow both 0/3 and 3/3 nodes were at revision 1 at the same time. Hiesenburg!!!

**Comment by eparis** [comment]
I waited at least 4 hours for it to settle (and this is how it settled)
